<?xml version="1.0"?>
<robot name="iboh" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Included URDF/XACRO Files -->
    <xacro:include filename="$(find iboh_description)/urdf/include/materials.urdf.xacro" />
    <xacro:include filename="$(find iboh_description)/urdf/include/hc-sr04.urdf.xacro" />

    <!-- Key Parameters -->
    <property name="chassis_mass" value="200" /> <!-- TODO insert a correct weight for iBoh -->
    <property name="chassis_length" value="0.325" /> 
    <property name="chassis_width" value="0.31" />
    <property name="chassis_height" value="0.102" />
    

    <!-- Root link of iBoh head -->
    <link name="iboh_link" /> 	

	<joint name="chassis_joint" type="fixed">
    	<origin xyz="0 0 0"
            	rpy="0 0 0"/>
    	<parent link="iboh_link" />
    	<child link="chassis_link" />
  	</joint>

    <link name="chassis_link">
		<inertial>
      		<mass value="${chassis_mass}"/>
      		<origin xyz="0 0 0"/>
      		<inertia ixx="1.0" ixy="0" ixz="0"
               		 iyy="1.0" iyz="0" izz="1.0" />
    	</inertial>
    	<visual>
      		<origin xyz="${chassis_length/2-0.03} 0 0"
              		rpy="${pi/2} 0 0" />
      		<geometry>
        		<mesh filename="package://iboh_description/meshes/iboh_chassis.stl"
             		scale="0.001 0.001 0.001" />
      		</geometry>
      		<material name="White" />
    	</visual>
		<collision>
			<origin xyz="0 0 ${chassis_height/2}"
					rpy="0 0 0" />
		  	<geometry>
		    	<box size="${chassis_length} ${chassis_width} ${chassis_height}" />
		  	</geometry>
		</collision>
  	</link>
  
	
    <!-- ZED camera-->
    <include filename="$(find zed_wrapper)/urdf/zed.urdf" />
    <joint name="zed_joint" type="fixed">
		<origin xyz="0.120 0.06 0.025"
				rpy="0 0 0"/>
		<parent link="chassis_link" />
		<child link="ZED_left_camera" />
	</joint>

   	<!-- Right Ultrasonic Sensor -->
    <xacro:hc-sr04 parent="chassis_link" name_suffix="right">
		<origin xyz="0.121 -0.130 0.050" rpy="-${pi/2} 0 -0.2" />
	</xacro:hc-sr04>
	
    <!-- Center Ultrasonic Sensor -->
    <xacro:hc-sr04 parent="chassis_link" name_suffix="center">
		<origin xyz="0.125 0 0.070" rpy="0 0 0" />
	</xacro:hc-sr04>	
    
    <!-- Left Ultrasonic Sensor -->
    <xacro:hc-sr04 parent="chassis_link" name_suffix="left">
		<origin xyz="0.121 0.130 0.050" rpy="-${pi/2} 0 0.2" />
	</xacro:hc-sr04>
	
    <!-- Add joint for Sensor_rear -->
    <xacro:hc-sr04 parent="chassis_link" name_suffix="rear">
		<origin xyz="-0.125 0 0.075" rpy="0 0 ${pi}" />
	</xacro:hc-sr04>
</robot>
